/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SsoCallbackController_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ผู้ใช้ทั้งหมด (เจ้าหน้าที่) */
        get: operations["MembersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** แถวใน members ของผู้เรียกเอง (id ที่ใช้เทียบกับ reporterId / claimantId) */
        get: operations["MembersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ค้นหา/กรองรายการ · `?mine=true` = เฉพาะที่ฉันแจ้ง */
        get: operations["ItemsController_list"];
        put?: never;
        post: operations["ItemsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายละเอียด (`secretAnswer` เห็นเฉพาะเจ้าของโพสต์/เจ้าหน้าที่) */
        get: operations["ItemsController_get"];
        put?: never;
        post?: never;
        delete: operations["ItemsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ItemsController_update"];
        trace?: never;
    };
    "/api/v1/items/{id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการฝั่งตรงข้ามที่อาจเป็นชิ้นเดียวกัน (เรียงตามคะแนน) */
        get: operations["ItemsController_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** เจ้าหน้าที่: ทั้งหมด · ผู้ใช้ทั่วไป (หรือ `?scope=mine`): คำขอที่ฉันยื่น + คำขอกับรายการของฉัน */
        get: operations["ClaimsController_list"];
        put?: never;
        post: operations["ClaimsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** อนุมัติ และออกรหัส 6 หลักให้ผู้ยื่น */
        post: operations["ClaimsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ClaimsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ผู้ส่ง/ผู้รับยืนยันการส่งมอบฝั่งตัวเอง ครบสองฝ่ายแล้วปิดคำขออัตโนมัติ */
        post: operations["ClaimsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** เจ้าหน้าที่ยืนยันรหัส 6 หลัก (กรณีส่งผ่านห้องเจ้าหน้าที่) */
        post: operations["ClaimsController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StatsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MemberView: {
            id: string;
            /** @description รหัสนักศึกษา (ถ้ามี) */
            studentId: string;
            fullName: string;
            email: string;
            phone: string;
            /**
             * @description สำเนาสิทธิ์ที่แมปจาก core role: admin = เจ้าหน้าที่
             * @enum {string}
             */
            role: "admin" | "user";
            createdAt: string;
        };
        ItemView: {
            id: string;
            /** @description รหัสที่แสดงให้ผู้ใช้ เช่น LF-2026-00001 */
            code: string;
            /** @enum {string} */
            reportType: "lost" | "found";
            name: string;
            description: string;
            category: string;
            location: string;
            faculty: string;
            building: string;
            room: string;
            /** @description วันที่ของหาย/พบของ (YYYY-MM-DD) */
            dateLost: string;
            /** @description เวลาโดยประมาณ (HH:MM เวลาไทย) */
            timeLost: string;
            /** @enum {string} */
            status: "found" | "searching" | "returned";
            /** @enum {string} */
            urgency: "normal" | "high";
            /** @description รูปหลัก (path /uploads/...) หรือค่าว่าง */
            imageUrl: string;
            thumbnails: string[];
            pinX?: number;
            pinY?: number;
            secretQuestion?: string;
            /** @description ส่งให้เฉพาะเจ้าของโพสต์และเจ้าหน้าที่ */
            secretAnswer?: string;
            /** @description id ใน members ของผู้แจ้ง */
            reporterId: string;
            reporterName: string;
            reporterStudentId: string;
            reporterPhone: string;
            reporterContact: string;
            createdAt: string;
            /** @description จำนวนคำขอที่ยังดำเนินการอยู่ */
            activeClaims: number;
        };
        MatchView: {
            item: components["schemas"]["ItemView"];
            /** @description 0-100 */
            score: number;
            reasons: string[];
        };
        CreateItemDto: {
            /** @enum {string} */
            reportType: "lost" | "found";
            name: string;
            description: string;
            category: string;
            location: string;
            faculty?: string;
            building?: string;
            room: string;
            /** @description YYYY-MM-DD */
            dateLost: string;
            /** @description HH:MM */
            timeLost: string;
            /** @enum {string} */
            urgency?: "normal" | "high";
            /** @description รูปแบบ data URL (JPG/PNG/WEBP ไม่เกิน 2 MB ต่อรูป) หรือ path /uploads/... ที่อัปโหลดไว้แล้ว */
            images?: string[];
            pinX?: number;
            pinY?: number;
            secretQuestion?: string;
            secretAnswer?: string;
            reporterName: string;
            /** @description รหัสนักศึกษา 10 หลัก (ไม่บังคับ) */
            reporterStudentId?: string;
            reporterPhone: string;
            reporterContact: string;
        };
        UpdateItemDto: {
            /** @enum {string} */
            status: "searching" | "found" | "returned";
        };
        DeletedView: {
            id: string;
            deleted: boolean;
        };
        CreateClaimDto: {
            /** Format: uuid */
            itemId: string;
            firstName: string;
            lastName: string;
            /** @description รหัสนักศึกษา 10 หลัก (ไม่บังคับ) */
            studentId?: string;
            department: string;
            /** @description วันที่นัด YYYY-MM-DD (เวลาไทย) */
            meetDate: string;
            /** @description เวลานัด HH:MM (เวลาไทย) */
            meetTime: string;
            meetLocation: string;
            contact: string;
            note?: string;
            /** @description คำตอบคำถามยืนยันความเป็นเจ้าของ (เมื่อขอรับคืนของที่มีคำถามลับ) */
            secretAnswer?: string;
            /**
             * Format: uuid
             * @description โพสต์ของผู้ยื่นเองที่เป็นเรื่องเดียวกัน เช่น เจ้าของเคยแจ้งหายไว้ — ปิดพร้อมกันเมื่อคืนสำเร็จ
             */
            linkedItemId?: string;
        };
        ClaimView: {
            /** @description UUID ใช้เรียก API */
            requestId: string;
            /** @description รหัสที่แสดงให้ผู้ใช้ เช่น REQ-1A2B3C4D */
            requestCode: string;
            itemId: string;
            itemName: string;
            itemCode: string;
            /**
             * @description found = เจ้าของขอรับคืน · lost = ผู้พบแจ้งส่งคืน
             * @enum {string}
             */
            claimType: "lost" | "found";
            claimantId: string;
            claimerName: string;
            studentId: string;
            department: string;
            /** @description วันเวลานัด "YYYY-MM-DD HH:MM" เวลาไทย */
            claimDateTime: string;
            claimLocation: string;
            contact: string;
            note: string;
            requestDate: string;
            /** @enum {string} */
            status: "pending" | "approved" | "at_office" | "rejected" | "completed";
            /** @description ส่งให้เฉพาะเจ้าหน้าที่ */
            secretAnswerGiven?: string;
            /** @description ส่งให้เฉพาะผู้ยื่นคำขอและเจ้าหน้าที่ */
            handoverCode?: string;
            /** @description ส่งให้เฉพาะเจ้าของโพสต์และเจ้าหน้าที่ */
            pickupCode?: string;
            approvedAt?: string;
            droppedOffAt?: string;
            handedOverAt?: string;
            handedOverBy?: string;
            giverConfirmedAt?: string;
            receiverConfirmedAt?: string;
            linkedItemId?: string;
        };
        VerifyCodeDto: {
            code: string;
        };
        ItemStatsView: {
            totalItems: number;
            searching: number;
            found: number;
            returned: number;
            pendingClaims: number;
            totalUsers: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SsoCallbackController_callback: {
        parameters: {
            query: {
                access_token: string;
                token_type?: "Bearer" | "bearer";
                expires_in?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MembersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"];
                };
            };
        };
    };
    ItemsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค้นหาในชื่อ รหัส สถานที่ และรายละเอียด */
                q?: string;
                status?: "searching" | "found" | "returned";
                type?: "lost" | "found";
                category?: string;
                /** @description true = เฉพาะรายการที่ฉันแจ้ง */
                mine?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ItemsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemView"];
                };
            };
        };
    };
    ItemsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemView"];
                };
            };
        };
    };
    ItemsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedView"];
                };
            };
        };
    };
    ItemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemView"];
                };
            };
        };
    };
    ItemsController_matches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClaimsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                scope?: "mine" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClaimsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClaimDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
        };
    };
    ClaimsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
        };
    };
    ClaimsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
        };
    };
    ClaimsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
        };
    };
    ClaimsController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
        };
    };
    StatsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemStatsView"];
                };
            };
        };
    };
}
